sudo: required
services:
  - docker

before_install:
  - docker build -t volodymyrkolomiiets/docker-react -f Dockerfile.dev .

script:
  - docker run volodymyrkolomiiets/docker-react npm run test -- --coverage
